name: Reusable · Add issues to Org Project #6

on:
  workflow_call:
    secrets:
      ORG_PROJECT_TOKEN:
        required: true
    inputs:
      org_login:
        description: "Organization login"
        type: string
        required: true
        default: graymatterresources
      project_number:
        description: "Org Project number"
        type: number
        required: true
        default: 6

jobs:
  add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Resolve ProjectV2 ID
        env:
          GH_TOKEN: ${{ secrets.ORG_PROJECT_TOKEN }}
          ORG_LOGIN: ${{ inputs.org_login }}
          PROJECT_NUMBER: ${{ inputs.project_number }}
        run: |
          PROJECT_ID=$(gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org) {
                projectV2(number: $number) { id }
              }
            }' \
            -f org="$ORG_LOGIN" -F number="$PROJECT_NUMBER" \
            --jq '.data.organization.projectV2.id')
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Add issue to Project
        env:
          GH_TOKEN: ${{ secrets.ORG_PROJECT_TOKEN }}
        run: |
          gh api graphql -f query='
            mutation($project: ID!, $item: ID!) {
              addProjectV2ItemById(input: { projectId: $project, contentId: $item }) {
                item { id }
              }
            }' \
            -f project="${PROJECT_ID}" \
            -f item="${{ github.event.issue.node_id }}"
