name: Add issues to Org Project #6

on:
  issues:
    types: [opened, reopened, labeled]  # add 'edited' if you want edits to trigger too

permissions:
  contents: read
  issues: read
  projects: write

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.ORG_PROJECT_TOKEN }}   # Org-level secret (see below)
      ORG_LOGIN: graymatterresources
      PROJECT_NUMBER: 6
    steps:
      - name: Resolve ProjectV2 ID
        id: proj
        run: |
          PROJECT_ID=$(gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org) {
                projectV2(number: $number) { id }
              }
            }' -f org="$ORG_LOGIN" -F number="$PROJECT_NUMBER" --jq '.data.organization.projectV2.id')
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_OUTPUT

      - name: Add issue to Project
        if: ${{ github.event.issue.node_id != '' }}
        run: |
          gh api graphql -f query='
            mutation($project: ID!, $item: ID!) {
              addProjectV2ItemById(input: { projectId: $project, contentId: $item }) {
                item { id }
              }
            }' \
            -f project="${{ steps.proj.outputs.PROJECT_ID }}" \
            -f item="${{ github.event.issue.node_id }}"
